export const sampleProducts = [
  {
    id: 'p001',
    name: 'Wireless Bluetooth Headphones',
    description: 'Over-ear noise-cancelling headphones with 30h battery life.',
    price: 129.99,
    category: 'Audio',
    brand: 'Sony',
    stock: 25,
  },
  {
    id: 'p002',
    name: 'Smartphone 6.5" AMOLED',
    description: '128GB storage, dual SIM, 5G enabled, fast charging.',
    price: 499.99,
    category: 'Mobile',
    brand: 'Samsung',
    stock: 15,
  },
  {
    id: 'p003',
    name: 'Portable Bluetooth Speaker',
    description: 'Waterproof speaker with 10h battery life.',
    price: 59.95,
    category: 'Audio',
    brand: 'JBL',
    stock: 50,
  },
  {
    id: 'p004',
    name: 'Smartwatch with GPS',
    description: 'Fitness tracking, sleep monitoring, heart rate sensor.',
    price: 149.0,
    category: 'Wearables',
    brand: 'Fitbit',
    stock: 18,
  },
  {
    id: 'p005',
    name: 'Laptop 15.6" i5 12th Gen',
    description: '8GB RAM, 512GB SSD, Windows 11, lightweight.',
    price: 699.99,
    category: 'Computers',
    brand: 'Dell',
    stock: 10,
  },
  {
    id: 'p006',
    name: '4K UHD Smart TV 55"',
    description: 'HDR, voice control, pre-installed apps, 3 HDMI ports.',
    price: 549.99,
    category: 'TV',
    brand: 'LG',
    stock: 7,
  },
  {
    id: 'p007',
    name: 'Wireless Charging Pad',
    description: '10W fast wireless charger compatible with most phones.',
    price: 19.99,
    category: 'Accessories',
    brand: 'Anker',
    stock: 100,
  },
  {
    id: 'p008',
    name: 'USB-C Hub Adapter',
    description: '5-in-1 hub with HDMI, USB 3.0, SD card reader.',
    price: 34.99,
    category: 'Accessories',
    brand: 'Baseus',
    stock: 40,
  },
  {
    id: 'p009',
    name: 'Noise Cancelling Earbuds',
    description: 'True wireless with ANC, case provides 24h playback.',
    price: 89.0,
    category: 'Audio',
    brand: 'OnePlus',
    stock: 30,
  },
  {
    id: 'p010',
    name: '1080p HD Webcam with Microphone',
    description: 'Plug-and-play webcam for streaming and video calls.',
    price: 39.99,
    category: 'Accessories',
    brand: 'Logitech',
    stock: 22,
  },
];
